### PR TITLE
remove clippy dependency

### PR DESCRIPTION
**Pull request by little-dude**
that should fix the travis failure

### CODE REVIEW

**Comment by patrickisgreene** [comment]
Yes please! this is what i wanted to do but forgot. Their going through a lot of churn right now and i think we should wait it out until they get the (not beta) rustup component.

**Comment by patrickisgreene** [comment]
Oh , hit the Close instead of comment

**Comment by little-dude** [comment]
clippy v0.0.212 does not build on rustc 1.29.0-nightly (6a1c0637c 2018-07-23): https://travis-ci.org/xi-frontend/xi-term/jobs/409415745

Maybe we should install `clippy-preview` instead? I should also make the build faster.

**Review by patrickisgreene — APPROVED** [review]

**Comment by patrickisgreene** [comment]
I think we should install the clippy-preview component during the travis build but i was unable to get it work on my maching either. exact same errors and everything

**Comment by little-dude** [comment]
victory \o/
https://travis-ci.org/xi-frontend/xi-term/jobs/409418018

**Comment by little-dude** [comment]
>  i was unable to get it work on my maching either. exact same errors and everything

That's weird, `rustup component add clippy-preview --toolchain=nightly` should not attempt to compile clippy. It should install the binary directly.

**Comment by patrickisgreene** [comment]
Hmm, i wonder when the last time i ran rustup update was :wink: .

**Pull request merged**
