### PR TITLE
Name change

### PR DESCRIPTION
**Pull request by patrickisgreene**
As discussed in #47.

### CODE REVIEW

**Comment by ryukinix** [comment]
The nightly is still failing, I did forget how I fixed that, but if I remember correctly this have some relation to update the Cargo.lock and some code of the API. I did this on xim

**Comment by ryukinix** [comment]
We should fix that on this PR or only fix that later? I'll wait for the @little-dude review to get merge this

**Comment by patrickisgreene** [comment]
Yeah i'm working on fixing travis now, if i get that done before little-dude reviews i could add it to this but i think it's best to seperate into PR's

**Comment by patrickisgreene** [comment]
I was able to fix travis by updating clippy and Cargo.lock to reflect the change's(also fixing a few clippy lint's)

@ryukinix I looked through xim, it seem's you fixed it by removing cllippy, you can change this line in .travis.yml
```
bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo build; else cargo build ; fi'
```
to 
```
bash -c 'cargo build` 
``` 
if you want to simplify things a little bit.

**Comment by little-dude** [comment]
@ryukinix don't wait for me for this. I won't be able to look at anything for at least two weeks, I just browse my notifications once in a while from a phone. I don't want to slow you down.

**Review by ryukinix — APPROVED** [review]
I'm ok with that, we need merge it.

**Pull request merged**
