### PR TITLE
Add delete key functionality

### PR DESCRIPTION
**Pull request by 1011X**

### CODE REVIEW

**Comment by patrickisgreene** [comment]
I think clippy is failing because of this rust-lang-nursery/rust-clippy #2532 updating clippy should fix

**Review by patrickisgreene — COMMENTED** [review]
Thanks for your work!  seem's good to me, Could you do me a favor and update clippy to 0.0.193 and see if that fix's travis

**Comment by 1011X** [comment]
Sure thing!

**Review by patrickisgreene — APPROVED** [review]

**Comment by patrickisgreene** [comment]
Thanks again!

**Pull request merged**
